apiVersion: v1
kind: Pod
metadata:
  name: db-test
  labels:
    app: db-test
spec:
  containers:
    - name: db-test-container
      image: mysql:8.0.36
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap
