apiVersion: v1
kind: Pod
metadata:
  name: db-test
  labels:
    app: db-test
spec:
  containers:
    - name: db-test-container
      image: mysql:8.0.36
      ports:
        - containerPort: 3306
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "7777"

        - name: "MYSQL_DATABASE"
          value: "test"

        - name: "MYSQL_PASSWORD"
          value: "7777"
